spring:
  datasource:
    url: jdbc:mysql://cdb-1i8po9jg.cd.tencentcdb.com:10126/medical?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liujinwei0213
  thymeleaf:
    cache: false
    encoding: utf-8
mybatis:
   mapper-locations: classpath:mapper/*Mapper.xml

